// Type declarations for Nitro virtual modules generated by nuxt-cms at build time.
// These modules are created by addServerTemplate in src/module.ts and are only
// available inside the Nitro/server bundle — not at type-check time for the root
// tsconfig. These ambient declarations silence the "Cannot find module" errors.

declare module '#my-module/db.mjs' {
  // The user's Drizzle db instance; typed as `any` because the specific schema
  // is defined by the consuming application, not by this module.
  const db: any
  export default db
}

declare module '#my-module/collections.mjs' {
  import type { CollectionDefinition } from './src/runtime/types'
  export const collections: CollectionDefinition[]
}
